[package]
name = "hexify"
version = "0.0.1"
edition = "2024"
description = "A simple command line color quantizer for theming your wallpapers"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
env_logger = "0.11.8"
image = "0.25.6"
log = "0.4.27"
